batch_size : 1024
num_workers : 8
learning_rate: 1e-4
weight_decay: 0.01
warmup_epochs: 1.0
num_epochs: 10
save_top_k: 5
every_n_epochs: 1
val_check_interval: 0.25
check_val_every_n_epoch: 1
limit_val_batches: 1000
